import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { NavigationMenuDemo } from "./-components/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner"
import WrapperCom from "./-components/WrapperCom";
import TanStackProviders from "../providers/TanStackProvider";
import Footer from "./-components/Footer/Footer";


const exo = Exo({

  subsets: ["latin"],
  weight: ['400', '500']
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={exo.className}
      >

        {/*navbar */}
       
        <div className="continer max-w-[1250px] mx-auto">

          <TanStackProviders>
             <WrapperCom>
          <NavigationMenuDemo />
        </WrapperCom>
            {children}
            <Toaster />
          
          </TanStackProviders>

        </div>
          <Footer/>
      </body>
    </html>
  );
}
